"""Initial database creation

Revision ID: e4fe178de8e5
Revises: 
Create Date: 2025-09-13 13:31:11.672821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4fe178de8e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_key', sa.String(length=64), nullable=False),
    sa.Column('courier_type', sa.String(length=64), nullable=False),
    sa.Column('tracking_url', sa.String(length=512), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_accounts_account_key'), 'courier_accounts', ['account_key'], unique=True)
    op.create_index(op.f('ix_courier_accounts_courier_type'), 'courier_accounts', ['courier_type'], unique=False)
    op.create_table('courier_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tracking_url_template', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('print_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('awb_count', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('romania_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judet', sa.String(length=255), nullable=True),
    sa.Column('localitate', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=32), nullable=True),
    sa.Column('tip_artera', sa.String(length=64), nullable=True),
    sa.Column('nume_strada', sa.String(length=512), nullable=True),
    sa.Column('cod_postal', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localitate_judet', 'romania_addresses', ['localitate', 'judet'], unique=False)
    op.create_index(op.f('ix_romania_addresses_cod_postal'), 'romania_addresses', ['cod_postal'], unique=False)
    op.create_index(op.f('ix_romania_addresses_judet'), 'romania_addresses', ['judet'], unique=False)
    op.create_index(op.f('ix_romania_addresses_localitate'), 'romania_addresses', ['localitate'], unique=False)
    op.create_index(op.f('ix_romania_addresses_nume_strada'), 'romania_addresses', ['nume_strada'], unique=False)
    op.create_index(op.f('ix_romania_addresses_sector'), 'romania_addresses', ['sector'], unique=False)
    op.create_index(op.f('ix_romania_addresses_tip_artera'), 'romania_addresses', ['tip_artera'], unique=False)
    op.create_table('store_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_courier', sa.String(length=64), nullable=True),
    sa.Column('default_courier_account', sa.String(length=64), nullable=True),
    sa.Column('dpd_pickup_location_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('shared_secret', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('pii_source', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('paper_size', sa.String(length=16), nullable=False),
    sa.Column('dpd_client_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('courier_category_map',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('courier_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['courier_categories.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'courier_key')
    )
    op.create_table('courier_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_name', sa.String(length=255), nullable=False),
    sa.Column('account_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_key'], ['courier_accounts.account_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_mappings_shopify_name'), 'courier_mappings', ['shopify_name'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('shopify_order_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('financial_status', sa.String(length=64), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('payment_gateway_names', sa.Text(), nullable=True),
    sa.Column('mapped_payment', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shopify_status', sa.String(length=64), nullable=True),
    sa.Column('fulfilled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shipping_name', sa.Text(), nullable=True),
    sa.Column('shipping_address1', sa.Text(), nullable=True),
    sa.Column('shipping_address2', sa.Text(), nullable=True),
    sa.Column('shipping_phone', sa.String(length=64), nullable=True),
    sa.Column('shipping_city', sa.String(length=255), nullable=True),
    sa.Column('shipping_zip', sa.String(length=32), nullable=True),
    sa.Column('shipping_province', sa.String(length=255), nullable=True),
    sa.Column('shipping_country', sa.String(length=255), nullable=True),
    sa.Column('address_status', sa.String(length=32), nullable=False),
    sa.Column('address_score', sa.Integer(), nullable=True),
    sa.Column('address_validation_errors', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('assigned_courier', sa.String(length=64), nullable=True),
    sa.Column('is_on_hold_shopify', sa.Boolean(), nullable=False),
    sa.Column('derived_status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_address_status'), 'orders', ['address_status'], unique=False)
    op.create_index(op.f('ix_orders_financial_status'), 'orders', ['financial_status'], unique=False)
    op.create_index(op.f('ix_orders_is_on_hold_shopify'), 'orders', ['is_on_hold_shopify'], unique=False)
    op.create_index(op.f('ix_orders_processing_status'), 'orders', ['processing_status'], unique=False)
    op.create_index(op.f('ix_orders_shopify_order_id'), 'orders', ['shopify_order_id'], unique=True)
    op.create_index(op.f('ix_orders_shopify_status'), 'orders', ['shopify_status'], unique=False)
    op.create_table('print_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_log_id', sa.Integer(), nullable=True),
    sa.Column('order_name', sa.String(length=64), nullable=True),
    sa.Column('awb', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['print_log_id'], ['print_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_log_entries_awb'), 'print_log_entries', ['awb'], unique=False)
    op.create_table('store_category_map',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['store_categories.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'store_id')
    )
    op.create_table('fulfillment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shopify_fulfillment_order_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('hold_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_orders_order_id'), 'fulfillment_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_orders_shopify_fulfillment_order_id'), 'fulfillment_orders', ['shopify_fulfillment_order_id'], unique=True)
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_sku'), 'line_items', ['sku'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('fulfillment_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shopify_fulfillment_id', sa.String(length=50), nullable=True),
    sa.Column('awb', sa.String(length=64), nullable=True),
    sa.Column('courier_specific_data', sa.JSON(), nullable=True),
    sa.Column('courier', sa.String(length=64), nullable=True),
    sa.Column('account_key', sa.String(length=32), nullable=True),
    sa.Column('paper_size', sa.String(length=16), nullable=True),
    sa.Column('printed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=255), nullable=True),
    sa.Column('last_status_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('derived_status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_awb'), 'shipments', ['awb'], unique=False)
    op.create_index(op.f('ix_shipments_courier'), 'shipments', ['courier'], unique=False)
    op.create_index(op.f('ix_shipments_last_status'), 'shipments', ['last_status'], unique=False)
    op.create_index(op.f('ix_shipments_printed_at'), 'shipments', ['printed_at'], unique=False)
    op.create_index(op.f('ix_shipments_shopify_fulfillment_id'), 'shipments', ['shopify_fulfillment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_shopify_fulfillment_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_printed_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_last_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_courier'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_awb'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_line_items_sku'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_fulfillment_orders_shopify_fulfillment_order_id'), table_name='fulfillment_orders')
    op.drop_index(op.f('ix_fulfillment_orders_order_id'), table_name='fulfillment_orders')
    op.drop_table('fulfillment_orders')
    op.drop_table('store_category_map')
    op.drop_index(op.f('ix_print_log_entries_awb'), table_name='print_log_entries')
    op.drop_table('print_log_entries')
    op.drop_index(op.f('ix_orders_shopify_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_shopify_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_processing_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_on_hold_shopify'), table_name='orders')
    op.drop_index(op.f('ix_orders_financial_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_address_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_courier_mappings_shopify_name'), table_name='courier_mappings')
    op.drop_table('courier_mappings')
    op.drop_table('courier_category_map')
    op.drop_table('stores')
    op.drop_table('store_categories')
    op.drop_index(op.f('ix_romania_addresses_tip_artera'), table_name='romania_addresses')
    op.drop_index(op.f('ix_romania_addresses_sector'), table_name='romania_addresses')
    op.drop_index(op.f('ix_romania_addresses_nume_strada'), table_name='romania_addresses')
    op.drop_index(op.f('ix_romania_addresses_localitate'), table_name='romania_addresses')
    op.drop_index(op.f('ix_romania_addresses_judet'), table_name='romania_addresses')
    op.drop_index(op.f('ix_romania_addresses_cod_postal'), table_name='romania_addresses')
    op.drop_index('ix_localitate_judet', table_name='romania_addresses')
    op.drop_table('romania_addresses')
    op.drop_table('print_logs')
    op.drop_table('courier_categories')
    op.drop_index(op.f('ix_courier_accounts_courier_type'), table_name='courier_accounts')
    op.drop_index(op.f('ix_courier_accounts_account_key'), table_name='courier_accounts')
    op.drop_table('courier_accounts')
    # ### end Alembic commands ###
